extern alias @private;
global using @private::JetBrains.Annotations;
global using System;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Linq;
global using System.Collections.Generic;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Runtime.InteropServices;
global using System.Runtime.CompilerServices;
global using static Talkward.Helpers;